// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzr79ul6c5r1O9T6SYXKOj75df3cptEiM',
    appId: '1:25055810866:web:b131e1ee0de1b3a322f32b',
    messagingSenderId: '25055810866',
    projectId: 'post-it-a5b56',
    authDomain: 'post-it-a5b56.firebaseapp.com',
    storageBucket: 'post-it-a5b56.appspot.com',
    measurementId: 'G-W8DSMEQR8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDig1fkolVQuHtUqSEisS73k06egGmk0ng',
    appId: '1:25055810866:android:4a4f880c2d928fc122f32b',
    messagingSenderId: '25055810866',
    projectId: 'post-it-a5b56',
    storageBucket: 'post-it-a5b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaeaJBHIHRzbR4CLNSPEREeZ0g_nQhKXA',
    appId: '1:25055810866:ios:c9e71e6b80676b3422f32b',
    messagingSenderId: '25055810866',
    projectId: 'post-it-a5b56',
    storageBucket: 'post-it-a5b56.appspot.com',
    iosClientId: '25055810866-7qc0n13t1mehlukkacmkjpd5jdp3p35j.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitClone',
  );
}
